num_iters: 5000
num_warmup_iters: 300
x_lr: !!float 5e-4
k_lr: !!float 5e-4
s_lr: 0.01
img_size: &HQ_SIZE [678,1024]           #[720,1280]
warmup_k_path:    experiments/pretrained/kernel.pth  #experiments/REDS_woVAE/models/latest_G.pth
reg_noise_std: !!float 0.001

ImageDIP:
    input_nc: 8
    output_nc: 3
    nf: 64
    norm: none
    padding_type: reflect

KernelDIP:
    nf: 64
    n_blocks: 6
    padding_type: reflect
    use_dropout: false
    kernel_dim: 512
    norm: none
EDnet:
    batch_size: 6
    nz : 250
    gamma_factor: 2.2
    K: 25
    img_size: *HQ_SIZE
    nef: 32
    kernel_img : [33,33]
    n_iters : 30
    sat_threshold : 0.99
    reg_factor : 1e-3
    optim_iters : True
    dilation : False
    smoothing : True
    erosion : True
    savei : data1/xin
KernelWizard:
  pretrained: experiments/MY_PRO/models/latest_G.pth
  input_nc: 3
  nf: 64
  front_RBs: 10
  back_RBs: 20
  N_frames: 1
  kernel_dim: 512
  img_size: *HQ_SIZE
  use_vae: false
  KernelExtractor:
    norm: none
    use_sharp: true
    n_blocks: 4
    padding_type: reflect
    use_dropout: false
  Adapter:
    norm: none
    use_dropout: false
