#### general settings
name: MY_PRON
use_tb_logger: true
model: image_base
distortion: deblur
scale: 1
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: REDS
    mode: REDS
    interval_list: [1]
    dataroot_HQ: datasets/REDS/train_sharp_wval.lmdb
    dataroot_LQ: datasets/REDS/train_blur_wval.lmdb
    cache_keys: ~

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 24
    HQ_size: &HQ_SIZE 256
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
KernelWizard:
  input_nc: 3
  nf: 64
  front_RBs: 10
  back_RBs: 32
  N_frames: 1
  kernel_dim: 512
  img_size: *HQ_SIZE

  use_vae: false
  KernelExtractor:
    norm: none
    use_sharp: true
    n_blocks: 4
    padding_type: reflect
    use_dropout: false
  Adapter:
    norm: none
    use_dropout: false

ImageDIP:
    input_nc: 8
    output_nc: 3
    nf: 64
    norm: none
    padding_type: reflect

EDnet:
    batch_size: 24
    nz : 250
    gamma_factor: 2.2
    K: 25
    img_size: *HQ_SIZE
    nef: 32
    kernel_img : [33,33]
    n_iters : 30
    sat_threshold : 0.99
    reg_factor : 1e-3
    optim_iters : True
    dilation : False
    smoothing : True
    erosion : True
    savei : data1/xin
PREnet:
    img_size: *HQ_SIZE
    kernel_img : [29,29]

DImage:
    batch_size: 24
    image_size: 256
    conv_dim: 64

#### path
path:
  pretrain_model_G: experiments/MY_PRON/models/200000_G.pth
  strict_load: true
  resume_state: experiments/MY_PRON/training_state/200000.state #被存储的模型

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  x_lr: !!float 5e-4
  lrD : !!float 0.0004
  lr_scheme: CosineAnnealingLR_Restart    #MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [50000,
             100000,
             150000,
             200000,
             240000,
             300000,
             350000,
             400000,
             450000,
             490000,
             550000,
             600000]
  lr_gamma: 0.5
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-6
  img_size:  [256, 256]
  img_sizek:  [284, 284]
  reg_noise_std: !!float 0.001
  eps2: !!float 1e-6
  pixel_criterion: cb
  pixel_weight: 1.0
  kl_weight: 0.0
  val_freq: !!float 5e3

  manual_seed: 0


#### logger
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4

